### ISSUE TITLE
Wrong method used in newest css-addition?

### ISSUE THREAD

**Issue by MarcusSchwarz** [Taiko2k/GTK4PythonTutorial#15]
I might be wrong as I am literally only two hours into Python, but the line introduced here seems to be wrong:
https://github.com/Taiko2k/GTK4PythonTutorial/commit/c626634b73dec4f08436758192540da13768b47d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R297

This results in a compiler error: 
`TypeError: argument file: Expected Gio.File, but got str`

Changing it to `css_provider.load_from_path('style.css')` seems to do the trick.

**Comment by Taiko2k** [comment]
OK Ive committed your suggested change
