### ISSUE TITLE
add GridView example?

### ISSUE THREAD

**Issue by dhansmair** [Taiko2k/GTK4PythonTutorial#17]
Hi! 
Thank you for this amazing repository, it has been incredibly helpful to me.
Could you maybe provide an example on how to use the new GridView? (https://docs.gtk.org/gtk4/class.GridView.html)
It apparently replaces IconView.
I have spent hours but just can't get it to run...

**Comment by Taiko2k** [comment]
OK I've now added a section on that. See https://github.com/Taiko2k/GTK4PythonTutorial#using-gridview.

**Comment by dhansmair** [comment]
oh you really did that! awesome, thanks!
